---
title: "CV"
author: "Tamas Szilagyi"
date: "8 July 2016"
output: html_document
---

### Experience

```{r,results='asis', echo = F}
suppressPackageStartupMessages(library(googleVis))
# Source
source("data.R")

# Timeline chart example
op <- options(gvis.plot.tag='chart')
timel<-gvisTimeline(cv, barlabel="Position", rowlabel="Group",
                  start="StartDate", end="EndDate",
                  options=list(
                    timeline="{barLabelStyle:{fontSize:9},
                    showBarLabels: false}", width = 800))
plot(timel)
```

```{r,results='asis', echo = F}
Column1 <- gvisColumnChart(s1, options = 
                            list(vAxes="[{viewWindowMode:'explicit',
                                 viewWindow:{min:0, max:10}}]",
                                 colors="['#28BD8D']",
                                 legend = "none",
                                 title = "Web Analytics Skills",
                                 width = 250, height = 250))

Column2 <- gvisColumnChart(s2, options = 
                            list(vAxes="[{viewWindowMode:'explicit',
                                 viewWindow:{min:0, max:10}}]",
                                 colors="['#6A70DB']",
                                 legend = "none",
                                 title = "Online Advertising Skills",
                                 width = 250, height = 250))

Column3 <- gvisColumnChart(s3, options = 
                            list(vAxes="[{viewWindowMode:'explicit',
                                 viewWindow:{min:0, max:10}}]",
                                 colors="['#64A6ED']",
                                 legend = "none",
                                 title = "Data Science Skills",
                                 width = 250, height = 250))

Column4 <- gvisColumnChart(s4, options = 
                            list(vAxes="[{viewWindowMode:'explicit',
                                 viewWindow:{min:0, max:10}}]",
                                 colors="['#ED64C2']",
                                 legend = "none",
                                 title = "Coding Skills",
                                 width = 250, height = 250))

obj1<-gvisMerge(Column1, Column2, horizontal = TRUE)
obj2<-gvisMerge(Column3, Column4, horizontal = TRUE)
obj3<-gvisMerge(obj1, obj2, horizontal = FALSE)


plot(obj3)
```
